version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  app:
    build: .
    command: bundle exec rails s -p 3000
    volumes:
      - .:/app
      - bundle_gems:/usr/local/bundle
    ports:
      - "${PLANNER_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - app_worker
  
  app_worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle_gems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis:
  bundle_gems:
